# Generated by Django 4.2.1 on 2025-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("birthday", models.DateTimeField(blank=True, null=True)),
                ("mobile", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        default="default@example.com",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
