# Generated by Django 4.2.1 on 2025-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('sku_id', models.CharField(max_length=255, unique=True, verbose_name='商品id')),
                ('nums', models.IntegerField()),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
    ]
