# Generated by Django 4.2.1 on 2025-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="email",
            field=models.CharField(
                default="default@example.com", max_length=255, unique=True
            ),
        ),
    ]
