# Generated by Django 4.2.1 on 2025-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cart_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
